pybo-master/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

pybo-master/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo-master/pybo/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.detail, name='detail'),
    path('user/create/', views.user_create, name='user_create'),
    path('user/modify/<int:user_id>/', views.user_modify, name='user_modify'),
    path('user/delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('upload/<int:upload_id>/', views.upload_detail, name='upload_detail'),
    path('upload/create/', views.upload_create, name='upload_create'),
    path('delete/', views.delete, name='delete'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

pybo-master/common/models.py
from django.db import models

# Create your models here.

pybo-master/pybo/models.py
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    path = f'C:/Users/Administrator/PycharmProjects/pythonProject6/mysite/media/{instance.title}/{filename}.csv'
    return path

class User(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class UploadFileModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=user_directory_path)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Keyword(models.Model):
    number = models.TextField()
    unnamed = models.TextField()
    update = models.CharField(max_length=255)
    time = models.TextField()
    watch = models.TextField()
    search = models.TextField()
    leyword = models.TextField()
    video = models.TextField()
    url = models.URLField(blank=True, max_length=500)

    def __str__(self):
        return self.leyword

pybo-master/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

pybo-master/pybo/forms.py
from django import forms
from pybo.models import User, UploadFileModel


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': 'Name',
            'content': 'Content',
        }

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadFileModel
        fields = ('title', 'file',)

pybo-master/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

pybo-master/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import User, UploadFileModel
from .forms import UserForm, UploadFileForm
from .models import Keyword
from django.http import HttpResponse
import csv
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):

    user_list = User.objects.order_by('-create_date')
    context = {'user_list': user_list}
    return render(request, 'pybo/user_list.html', context)

def detail(request, user_id):

    user = User.objects.get(id=user_id)
    upload_list = UploadFileModel.objects.order_by('-create_date')
    context = {'user': user, 'upload_list': upload_list}
    return render(request, 'pybo/user_detail.html', context)

@login_required(login_url='common:login')
def user_create(request):

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.author = request.user
            user.author = request.user
            user.create_date = timezone.now()
            user.save()
            return redirect('pybo:index')
    else:
        form = UserForm()
    context = {'form': form}
    return render(request, 'pybo/user_form.html', context)

@login_required(login_url='common:login')
def user_modify(request, user_id):
    """
    pybo 질문수정
    """
    user = get_object_or_404(User, pk=user_id)
    if request.user != user.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', user_id=user.id)

    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.modify_date = timezone.now()  # 수정일시 저장
            user.save()
            return redirect('pybo:detail', user_id=user.id)
    else:
        form = UserForm(instance=user)
    context = {'form': form}
    return render(request, 'pybo/user_form.html', context)

@login_required(login_url='common:login')
def user_delete(request, user_id):
    """
    pybo 질문삭제
    """
    user = get_object_or_404(User, pk=user_id)
    if request.user != user.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', user_id=user.id)
    user.delete()
    return redirect('pybo:index')

def upload_index(request):

    upload_list = UploadFileModel.objects.order_by('-create_date')
    context = {'upload_list': upload_list}
    return render(request, 'pybo/upload_list.html', context)

def upload_detail(request, upload_id):

    Keyword.objects.all().delete()

    upload = UploadFileModel.objects.get(id=upload_id)
    def user_directory_path(instance, filename):
        path = f'{filename}'
        return path
    directory = user_directory_path(instance=upload.title, filename=upload.file)
    pathd = str(directory)

    file = open(pathd, encoding='utf-8')
    reader = csv.reader(file)
    print('-----', reader)
    list = []
    for row in reader:
        list.append(Keyword( number=row[0],
                             unnamed=row[1],
                             update=row[2],
                             time=row[3],
                             watch=row[4],
                             search=row[5],
                             leyword=row[6],
                             video=row[7],
                             url=row[8]
                             ))
    Keyword.objects.bulk_create(list)

    keyword_list = Keyword.objects.order_by()
    context = {'keyword_list' : keyword_list}
    return render(request, 'pybo/upload_detail.html', context)

@login_required(login_url='common:login')
def upload_create(request):

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            UploadFileModel.author = request.user
            return redirect('pybo:index')
    else:
        form = UploadFileForm()
    return render(request, 'pybo/upload_form.html', {'form': form})

def delete(self):

    UploadFileModel.objects.all().delete()
    str = 'all deleted fucker'
    return HttpResponse(str)

pybo-master/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

pybo-master/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

pybo-master/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

pybo-master/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

pybo-master/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">2P1K</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

pybo-master/templates/pybo/upload_check.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">File Check</h5>
    {% if question_list %}
    {% for question in question_list %}
        <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

pybo-master/templates/pybo/upload_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>keyword</th>
            </tr>
            </thead>
            <tbody>
            {% if keyword_list %}
            {% for keyword in keyword_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a>{{ keyword.leyword }}</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">등록된 파일이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
</div>
<div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>영상제목</th>
                <th>URL</th>
            </tr>
            </thead>
            <tbody>
            {% if keyword_list %}
            {% for keyword in keyword_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a>{{ keyword.video }}</a>
                </td>
                <td><a href="{{keyword.url}}">{{keyword.url}}</a></td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">등록된 파일이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
</div>

{% endblock %}

pybo-master/templates/pybo/upload_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">파일등록</h5>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
      </form>
</div>
{% endblock %}

pybo-master/templates/pybo/user_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ user.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ user.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ user.author.username }}</div>
                    <div>{{ user.create_date }}</div>
                </div>
            </div>
            {% if request.user == user.author %}
            <div class="my-3">
                <a href="{% url 'pybo:user_modify' user.id  %}"
                  class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                  data-uri="{% url 'pybo:user_delete' user.id  %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="container my-3">
        <table class="table">
            <thead>
            <tr class="text-center thead-dark">
                <th>No.</th>
                <th>Title</th>
                <th>ID</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% if upload_list %}
            {% for upload in upload_list %}
            <tr class="text-center">
                <td>{{ forloop.counter }}</td>
                <td class>
                    <a href="{% url 'pybo:upload_detail' upload.id %}">{{ upload.title }}</a>
                </td>
                <td>{{ upload.author.username }}</td>
                <td>{{ upload.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">등록된 파일이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <a href="{% url 'pybo:upload_create' %}" class="btn btn-primary">파일 등록하기</a>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

pybo-master/templates/pybo/user_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

pybo-master/templates/pybo/user_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>No.</th>
            <th>User</th>
            <th>ID</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        {% if user_list %}
        {% for user in user_list %}
        <tr class="text-center">
            <td>{{ forloop.counter }}</td>
            <td class>
                <a href="{% url 'pybo:detail' user.id %}">{{ user.subject }}</a>
            </td>
            <td>{{ user.author.username }}</td>
            <td>{{ user.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:user_create' %}" class="btn btn-primary">사용자 등록하기</a>
</div>

{% endblock %}